experiment_name: default_run
dataset: Imdb
dataset_path: ../datasets/aclImdb/
transformer_name: bert-base-cased
logging_dir: lightning_logs
model_type: sliding_window
batch_size: 1
num_classes: 7
early_stop_patience: 5
early_stop_delta: 0.0001
dropout: 0.2
learning_rate: 0.00005
hidden_size: 2048
window_size: 512
seed: 123
